### ISSUE TITLE
pyrfume data?

### ISSUE THREAD

**Issue by tvandera** [pyrfume/pyrfume#2]
Hi Rick,

Do you have any plans to release the pyrfume datasets?

Cheers,
Tom

**Comment by rgerkin** [comment]
@tvandera We do, but we have to work out some licensing issues.  Our initial plan is to subdivide the data into things we scraped from totally public openly licensed sources, and make these available first, and then figure out how to deal with the rest.  Are there are any datasets you are particularly interested in?

**Comment by contrebande-labs** [comment]
Hi Guys ! You might be interested in what we are doing [here](https://pdpp.contrebande.co). We are a bunch of people trying to clear the licenses on pretty much all the data that is mentionned in this project. We'd love to have your input !

**Comment by alexbw** [comment]
Contreban, so awesome to see other people interested in these problems! Your video was very nice, it's so delightful that you're working on this problem.

This might be interesting to you -- we have obtained permission from John Leffingwell to redistribute the Leffingwell PMP 2001 database. We've released it on Zenodo here: https://zenodo.org/record/4085098#.X462iJNKgws. The link says 'restricted', but that's just required because of the license we needed to apply. I very quickly approve all requests for download. I believe it will be mirrored in Pyrfume as well. 

We also do use the GoodScents dataset (you can read our paper on what we've done with the combined dataset here: https://arxiv.org/abs/1910.10685, I think it might be interesting to you based on very interesting video you posted). I am happy to chat about our experience learning about usage rights and cleaning details there.

**Comment by contrebande-labs** [comment]
Hi @alexbw I have requested access to your dump of the Leffingwell database (and I see just now that you granted it). I already have a dump of TGSC and we are in the process of trying to clear the rights and have a proper permissive (CC, probably) attached to it. The next steps are to publish an aggregated, merged, cleaned, updated dataset in a modern format (Protobuffers, probably) with a schema/ontology. I will send you an email directly should you want to voice or videochat sometimes.

**Comment by rgerkin** [comment]
@contrebandeco My colleagues (including @joelmainland and @alexbw) would like to meet with you to see how we can work together.    Is there a good contact email address that I can use to set this up?

**Comment by contrebande-labs** [comment]
Hi @rgerkin I'm sending you an email now ! Can't wait to talk to you all!

**Comment by rgerkin** [comment]
Most datasets available now.
