### ISSUE TITLE
Cannot use smiles_to_nspdk

### ISSUE THREAD

**Issue by churnikov** [pyrfume/pyrfume#4]
I'm trying to use `smiles_to_nspdk` from `pyrfume.features`

1. I found that variable `DATA_PATH` was changed to `DEFAULT_DATA_PATH` in `pyrfume.base`
2. `smiles_to_nspdk` uses `make_graphs` function. And this function needs `obabel_to_eden` function and `Vectorizer` class.

I can look through you commits, but may be you can point me to a certain commit, where these functions were removed?

**Comment by churnikov** [comment]
I think I've found [commit](https://github.com/pyrfume/pyrfume/commit/62973c39a8cb360b0e27a1fa6daafc8e17ffb2f3#diff-f75a75c39bc05e01fb9c1609395f1011L10) when this function was added, but it didn't have these function and class from the start 🤔

**Comment by rgerkin** [comment]
@churnikov 
Thanks for keeping up with this.  Adding a whole bunch of unit tests is on my to-do list for June before the ISOT meeting.  

The data path is now set in a configuration file for each user.  You can change it with
```
import pyrfume
pyrfume.set_data_path('/path/to/your/data')
```

I should not have pushed a new verison to PyPI from master as this new configuration has not been applied to other functions (like `smiles_to_nspdk`) that rely on the old path.  I will fix this today or tomorrow.  If possible I would also like to deprecate any dependence on `obabel` as `rdkit` is generally superior.

**Comment by churnikov** [comment]
So cool, that you respond so fast ❤️ 

I can open PR and fix this)

But I'd like to know, how can I replace open babel functions with rdkit functions?

**Comment by rgerkin** [comment]
@churnikov 
I fixed the basic imports just now, but getting Obabel+Eden to work will take a bit more time.  `obabel_to_eden` comes from Eden, and here was [my fork](https://github.com/rgerkin/EDeN) as of ~4 years ago.  You can see that there was a directory `converters` which had that function in it in `converter/molecule/obabel.py`.  But in the [head fork]( https://github.com/fabriziocosta/EDeN) maintained by the developers, there is no `converters` directory, and I'm not sure it relies on `obabel` anymore at all.  I assume it must use `Vectorizer` (which comes from `eden`) on some other object.  Maybe you can figure out how to fix just this line `eden_graph_generator = obabel_to_eden(smiles, file_format='smi') # Convert from SMILES to EdEN format` in `pyfrume.features` to use whatever the new `eden` scheme is for going from SMILES to a graph generator.

**Comment by churnikov** [comment]
I think I've found a workaround and will make PR soon

But I'd like to suggest a couple of things first:
1. Would mind using [poetry](https://python-poetry.org) instead of setup.py and requirements.txt? It's much more convenient
2. May I add [black](https://github.com/psf/black), [isort](https://isort.readthedocs.io/en/latest/) and [flake8](https://flake8.pycqa.org/en/latest/) configs?

I could add them as a separate PR if you want

**Comment by rgerkin** [comment]
@churnikov 
Yes, in retrospect it's ridiculous for me to be writing manual install and build scripts.  I've been waiting for "something" to emerge as the new Python dependency management solution that everyone uses.  Maybe it's time to take the plunge with poetry.  Is it still possible to `pip install -e .` or something similar for using the active development copy?  And making it conda installable down the road?  A lot of things don't play nicely together but if you're convinced it will work out let's do it.  

And I love all the linting / style-guide tools.  Add them all!

Thanks for contributing!

**Comment by rgerkin** [comment]
Fixed in #5.

**Comment by rgerkin** [comment]
@churnikov So it looks like `pip install -e` doesn't really have an obvious poetry equivalent (see [here](https://github.com/python-poetry/poetry/issues/34) where you can see from the up/down votes how many people this has annoyed!)  And no one has provided a satisfactory way to concurrently DEVELOP a package while also USING it in other projects without `pip install -e`.

So locally my workaround was to restore `setup.py` and run `python setup.py develop --install-dir=~/.local/lib/python3.7/site-packages/`.  Then at least I can import pyrfume everywhere else on my system, regardless of what virtual env I am in.  This doesn't require me reverting any of your work, because the `setup.py` only needs to exist locally for this to work (and only a small fraction of that file is necessary).

But still I'm wondering if there is some other work around I'm not seeing.  How do developers use their own packages while working on other projects without re-installing those packages every time, if using `poetry` rather than `setuptools`?

**Comment by rgerkin** [comment]
OK, maybe a symbolic link into site-packages is enough.  There will be no guarantees about dependency conflicts across packages that way, but that was already true of `pip install -e .`
