### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by rgerkin** [pyrfume/pyrfume#6]
@churnikov I am planning to do this using plain `unittest` like I do for [sciunit](http://github.com/scidash/sciunit) and other projects.  I also like to test my notebooks and have tools for doing that, but may switch to [papermill](https://github.com/nteract/papermill) for that which I started using elsewhere.  Any suggestions?

**Comment by churnikov** [comment]
Hey!

Sorry for such a slow reply 🤗 
I was reading about your tools in free time.

In my opinion, pytest is way easier to use, compared to unittest.

I've also found some tools that might find interesting, depending on the use case)
https://pypi.org/project/pytest-ipynb/
https://pytest-notebook.readthedocs.io/en/latest/

I also think that it's a nice idea to use papermill with pytest, because it has python API.

**Comment by rgerkin** [comment]
Some unit tests implemented (still using unittest, for ease of switching between projects) in 436e76a0341395d5777628b4adf93db97a6e41f5.  I will continue to revisit this and improve test coverage and the tests themselves.
